targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.

          # Any map true allows Firestore Map<dynamic, dynamic>
          any_map: true
